# Generated by Django 5.1.3 on 2024-11-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_participant_user_id_remove_participant_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='date',
        ),
    ]
