# Generated by Django 5.1.3 on 2024-11-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
