# Generated by Django 5.1.3 on 2024-11-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_bid_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
